### ISSUE TITLE
resender

### ISSUE THREAD

**Issue by poissson** [keselekpermen69/Telegram_Forwarder#2]
can the bot just re send the post ? not forward and show the source sender?

**Comment by keselekpermen69** [comment]
yes
just change the code on 

https://github.com/keselekpermen69/Telegram_Forwarder/blob/807d3015257022d8c76dabeaa91d0cacc6e93ae0/forwarder/modules/auto_forward.py#L16-L17

to [bot.send message](https://python-telegram-bot.readthedocs.io/en/stable/telegram.bot.html?highlight=send_message#telegram.Bot.send_message) with the correct parameters.
but keep in mind that it will not work for media's message like video, photo, etc. since those type have it own class.

you can read the [PTB docs](https://python-telegram-bot.readthedocs.io/en/stable/telegram.bot.htm) maybe you can find another solution since i haven't read the docs fully :"
